### ISSUE TITLE
What causes these Virus alerts?

### ISSUE THREAD

**Issue by 0lm** [bipinkrish/DeGourou#2]
The compiled exe for windows is detected as a virus by nearly 26 of 69 antivir on virustotal.
While the main repo zipped is clean.
It kind of feels like false alert, but 26 of 69 is a bit high to just convince myself of it being false alert.
Any idea what exactly causes these alerts in the compiled version?

**Comment by bipinkrish** [comment]
That's maybe the files it is writing to your device and the complex RSA algorithms it is using to decrypt.

And for your second point, VirusTotal cannot detect malicious code but can only detect malicious file, so checking for malicious code is of no use.

**Comment by bipinkrish** [comment]
Now You can use this on [Replit](https://replit.com/@bipinkrish/DeGourou) without worrying about the integrity/security or any other dependencies of this tool
